version: '3.8'

services:

  db:
    container_name: postgres-first-back
    image: postgres:14-alpine3.14
    restart: always

    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}

    volumes:
      - pgdata:/var/lib/postgresql/data

    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}

volumes:
  pgdata:
